cluster.name: ${CLUSTER_NAME}
node.name: architect-es
network.host: ${NETWORK_HOST}

xpack.license.self_generated.type: ${XPACK_LICENSE}
xpack.security.enabled: ${XPACK_SECURITY_ENABLED}
xpack.monitoring.collection.enabled: ${XPACK_MONITORING_COLLECTION_ENABLED}

discovery.type: ${DISCOVERY_TYPE}

discovery.seed_hosts: ${ELASTICSEARCH_HOST}
cluster.initial_master_nodes: architect-es
