name: elk-example
services:
  elasticsearch:
    build:
      args:
        ELK_VERSION: $ELK_VERSION
      context: elasticsearch/
    environment:
      ES_JAVA_OPTS: '-Xmx256m -Xms256m'
      ELASTIC_PASSWORD: changeme
      DISCOVERY_TYPE: single-node
      ELASTIC_DISCOVERY_TYPE: single-node
    reserved_name: elasticsearch
