name: ryan-cahill-a0/elk # TODO: change name after testing
description: ELK stack example
keywords:
  - architect
  - elk
  - elasticsearch
  - logstash
  - kibana

parameters:
  ELASTICSEARCH_USERNAME:
  ELASTICSEARCH_PASSWORD:
  ELASTICSEARCH_DISCOVERY_TYPE:
    required: false
  ELASTICSEARCH_CLUSTER_NAME:
    default: elasticsearch-cluster
  ES_JAVA_OPTS:
    default: "-Xmx2g -Xms2g"
  LS_JAVA_OPTS:
    default: "-Xmx512m -Xms512m"
  XPACK_LICENSE:
    default: trial

interfaces:
  logstash:
    description: logstash input
    url: ${{ services.logstash.interfaces.input.url }}
  kibana:
    description: kibana api
    url: ${{ services.kibana.interfaces.http.url }}

services:
  elasticsearch:
    language: java
    interfaces:
      http: 9200
      transport: 9300
    build:
      context: ./elasticsearch/config
      command: sysctl -w vm.max_map_count=262144 # TODO: use in initContainer
    environment:
      ES_JAVA_OPTS: ${{ parameters.ES_JAVA_OPTS }}
      ELASTIC_PASSWORD: ${{ parameters.ELASTICSEARCH_PASSWORD }}
      DISCOVERY_TYPE: ${{ parameters.ELASTICSEARCH_DISCOVERY_TYPE }}
      CLUSTER_NAME: ${{ parameters.ELASTICSEARCH_CLUSTER_NAME }}
      NETWORK_HOST: 0.0.0.0
      XPACK_LICENSE: ${{ parameters.XPACK_LICENSE }}
      XPACK_SECURITY_ENABLED: true
      XPACK_MONITORING_COLLECTION_ENABLED: true
      ELASTICSEARCH_HOST: ${{ services.elasticsearch.interfaces.http.host }}:${{ services.elasticsearch.interfaces.http.port }}
    volumes:
      elasticsearch_data:
        mount_path: /usr/share/elasticsearch/data

  logstash:
    language: ruby
    interfaces:
      http: 9600
      input: 5000
    build:
      context: ./logstash
    environment:
      LS_JAVA_OPTS: ${{ parameters.LS_JAVA_OPTS }}
      ELASTICSEARCH_URL: ${{ services.elasticsearch.interfaces.http.url }}
      ELASTICSEARCH_HOST: ${{ services.elasticsearch.interfaces.http.host }}:${{ services.elasticsearch.interfaces.http.port }}
      ELASTICSEARCH_USERNAME: ${{ parameters.ELASTICSEARCH_USERNAME }}
      ELASTICSEARCH_PASSWORD: ${{ parameters.ELASTICSEARCH_PASSWORD }}
      LOG_PORT: ${{ services.logstash.interfaces.input.port }}

  kibana:
    language: typescript
    interfaces:
      http: 5601
    build:
      context: ./kibana
    environment:
      ELASTICSEARCH_HOSTS: ${{ services.elasticsearch.interfaces.http.url }}
      ELASTICSEARCH_USERNAME: ${{ parameters.ELASTICSEARCH_USERNAME }}
      ELASTICSEARCH_PASSWORD: ${{ parameters.ELASTICSEARCH_PASSWORD }}
      MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: true
      SERVER_NAME: kibana
      SERVER_HOST: 0.0.0.0
