interfaces:
  elasticsearch: ${ components['ryan-cahill-a0/elk'].interfaces.elasticsearch.url }
  elasticsearch_transport: ${ components['ryan-cahill-a0/elk'].interfaces.elasticsearch_transport.url }
  logstash: ${ components['ryan-cahill-a0/elk'].interfaces.logstash.url }
  logstash_input: ${ components['ryan-cahill-a0/elk'].interfaces.logstash_input.url }
  kibana: ${ components['ryan-cahill-a0/elk'].interfaces.kibana.url }

components:
  ryan-cahill-a0/elk:
    extends: file:./architect.yml

    parameters:
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
