interfaces:
  logstash: ${{ components['ryan-cahill-a0/elk'].interfaces.logstash.url }}
  kibana: ${{ components['ryan-cahill-a0/elk'].interfaces.kibana.url }}

components:
  ryan-cahill-a0/elk:
    extends: file:./architect.yml

    parameters:
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
      ELASTICSEARCH_DISCOVERY_TYPE: single-node
