---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: ${SERVER_NAME}
server.host: ${SERVER_HOST}
elasticsearch.hosts: ${ELASTICSEARCH_HOSTS}
monitoring.ui.container.elasticsearch.enabled: ${MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED}

## X-Pack security credentials
#
elasticsearch.username: ${ELASTICSEARCH_USERNAME}
elasticsearch.password: ${ELASTICSEARCH_PASSWORD}
