http.host: 0.0.0.0
xpack.monitoring.elasticsearch.hosts: ${ELASTICSEARCH_URL}
xpack.monitoring.elasticsearch.password: ${ELASTICSEARCH_USERNAME}
xpack.monitoring.elasticsearch.username: ${ELASTICSEARCH_PASSWORD}
xpack.monitoring.enabled: true
