name: Test superset deployment

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  test_local:
    name: Superset local deployment
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ran local workflow"

  test_remote:
    name: Superset remote deployment
    if: github.base_ref == 'master'
    env:
      ACCOUNT_NAME: architect-ci
      ENVIRONMENT_NAME: example-environment
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ran remote workflow"
