name: Architect Production Deployment

on:
  release:
    types:
      - published

env:
  ARCHITECT_GENERATED: true
  ARCHITECT_PRODUCTION: true
  COMPONENT_FILE_PATH: docker-compose.yml
  ARCHITECT_ACCOUNT: architect-ryan
  COMPONENT_NAME: elk-example
  ENVIRONMENT_NAME: ryan-shared

jobs:
  architect_create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Architect CLI
        run: sudo npm install -g @architect-io/cli
      - name: Login to Architect Cloud
        run: architect login -e ${{ secrets.ARCHITECT_EMAIL }} -p ${{ secrets.ARCHITECT_PASSWORD }} # These secrets were created on your behalf
      - name: Register component w/ Architect
        run: architect register ${{ env.COMPONENT_FILE_PATH }} -t latest
      - name: Deploy component
        run: architect deploy --auto-approve -e ${{ env.ENVIRONMENT_NAME }} ${{ env.COMPONENT_NAME }}:latest
