name: Architect master Branch Deployment

on:
  push:
    branches:
      - master

env:
  ARCHITECT_GENERATED: true
  ARCHITECT_BRANCH: true
  COMPONENT_FILE_PATH: docker-compose.yml
  ARCHITECT_ACCOUNT: test-user-362
  COMPONENT_NAME: elk-example
  ENVIRONMENT_NAME: example-environment
  BRANCH_NAME: master
  ARCHITECT_CACHE_DIR: /tmp/workflow-cache

jobs:
  architect_create_branch_deployments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: ${{ env.ARCHITECT_CACHE_DIR }}
          key: ${{ runner.os }}-architect-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-architect-cache-
      - name: Install Architect CLI
        run: sudo npm install -g @architect-io/cli
      - name: Set Architect API endpoint
        run: architect config:set api_host https://api.dev.architect.io
      - name: Set Architect registry endpoint
        run: architect config:set registry_host registry.dev.architect.io
      - name: Login to Architect Cloud
        run: architect login -e ${{ secrets.ARCHITECT_EMAIL }} -p ${{ secrets.ARCHITECT_PASSWORD }} # These secrets were created on your behalf
      - name: Register component w/ Architect
        run: architect register ${{ env.COMPONENT_FILE_PATH }} -t latest --cache-directory ${{ env.ARCHITECT_CACHE_DIR }}
      - name: Deploy component
        run: architect deploy --auto-approve -e ${{ env.ENVIRONMENT_NAME }} ${{ env.COMPONENT_NAME }}:latest
